    - name: Install Android SDK
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools

        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip commandlinetools-linux-11076708_latest.zip

        mv cmdline-tools latest

        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH

        yes | sdkmanager --licenses || true

        # ⚠️ ВАЖНО: повторно принимаем лицензии после установки компонентов
        sdkmanager "platform-tools"
        sdkmanager "platforms;android-33"
        sdkmanager "build-tools;33.0.0"

        yes | sdkmanager --licenses || true
