    - name: Install Android SDK (FIX JAVA 17)
      run: |
        sudo apt update
        sudo apt install -y openjdk-17-jdk wget unzip

        export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
        export PATH=$JAVA_HOME/bin:$PATH

        java -version

        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools

        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip commandlinetools-linux-11076708_latest.zip

        mv cmdline-tools latest

        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH

        yes | sdkmanager --licenses || true

        sdkmanager "platform-tools"
        sdkmanager "platforms;android-33"
        sdkmanager "build-tools;33.0.2" || true

        yes | sdkmanager --licenses || true
